version: '3.5'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    container_name: 'postgres'
    restart: always
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./back/src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  front:
    build:
      context: ./front
    ports:
      - "3001:3001"
    depends_on:
      - back
volumes:
  pg-data:
